security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
      
        ROLE_BOARD:      [ROLE_ADMIN, ROLE_PROF,ROLE_ETUDIANT]
        ROLE_ADMIN : ROLE_ADMIN
        ROLE_PROF : ROLE_PROF
        ROLE_ETUDIANT : ROLE_ETUDIANT

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: acme_login_success_handler
                failure_path:   null
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       
       