<?php

namespace Gestion\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfRepository extends EntityRepository
{
}
